### ISSUE TITLE
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'

### ISSUE THREAD

**Issue by Veldkornet** [dmulcahey/zha-network-card#20]
I seem to be getting the following after updating HA to 0.115.2

```
2020-09-20 11:05:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/zha_map/__init__.py", line 137, in build
    await self.scan_device(seed)
  File "/config/custom_components/zha_map/__init__.py", line 226, in scan_device
    nei = await Neighbour.scan_device(device)
  File "/config/custom_components/zha_map/neighbour.py", line 115, in scan_device
    await r.scan()
  File "/config/custom_components/zha_map/neighbour.py", line 131, in scan
    neighbors = val.NeighborTableList
AttributeError: 'Neighbors' object has no attribute 'NeighborTableList'
```

**Comment by Adminiuga** [comment]
The zha_map it s going to be broken with the latest release, as some of the features are being moved into the core. I'll push the updated version in a few days
